In [1]:
import pandas as pd;
import numpy as np
import statsmodels.api as sm
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline

FinalData = pd.read_csv('finalDate.csv')

In [2]:
FinalData

,Unnamed: 0,Price,Year,Mileage,City,State,Make,Model,Original Price,Vehicle Type,serviceTime,DepreciationRate,Gdp,Population
0,0,15893,2015,30608,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,3,0.500094,490074,"2,340,814"
1,1,13950,2015,95099,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,3,0.438955,490074,"2,340,814"
2,2,29900,2015,24384,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,3,0.782723,490074,"2,340,814"
3,3,26505,2014,42980,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.693848,490074,"2,340,814"
4,4,16400,2017,25446,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,1,0.516048,490074,"2,340,814"
5,5,18991,2014,33658,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,4,0.597577,490074,"2,340,814"
6,6,34000,2014,63120,HOUSTON,TX,GMC,SIERRA,35900,Truck,4,0.947075,490074,"2,340,814"
7,7,27988,2014,30321,HOUSTON,TX,GMC,SIERRA,35900,Truck,4,0.779610,490074,"2,340,814"
8,8,17986,2015,21448,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,3,0.654751,490074,"2,340,814"
9,9,24977,2014,29344,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.653848,490074,"2,340,814"
10,10,34459,2015,94129,HOUSTON,TX,FORD,F-1504WD,34695,Truck,3,0.993198,490074,"2,340,814"
11,11,14225,2016,36317,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,2,0.447609,490074,"2,340,814"
12,12,9999,2004,167182,HOUSTON,TX,JEEP,GRAND,31695,SUV,14,0.315476,490074,"2,340,814"
13,13,15995,2014,40576,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,4,0.503304,490074,"2,340,814"
14,14,15449,2015,34834,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,3,0.486123,490074,"2,340,814"
15,15,15995,2008,83493,HOUSTON,TX,FORD,F-1504WD,34695,Truck,10,0.461017,490074,"2,340,814"
16,16,9499,2008,115338,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,10,0.345795,490074,"2,340,814"
17,17,30789,2014,32943,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.805995,490074,"2,340,814"
18,18,12995,2013,90214,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,5,0.473062,490074,"2,340,814"
19,19,29988,2014,83803,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.785026,490074,"2,340,814"
20,20,21493,2017,36715,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,1,0.782417,490074,"2,340,814"
21,21,25884,2013,35832,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,5,0.677592,490074,"2,340,814"
22,22,12491,2010,71120,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,8,0.454714,490074,"2,340,814"
23,23,24525,2011,123507,HOUSTON,TX,GMC,SIERRA,35900,Truck,7,0.683148,490074,"2,340,814"
24,24,32998,2014,43840,HOUSTON,TX,GMC,SIERRA,35900,Truck,4,0.919164,490074,"2,340,814"
25,25,21500,2015,37699,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,3,0.782672,490074,"2,340,814"
26,26,4495,2004,141014,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,14,0.163633,490074,"2,340,814"
27,27,28488,2016,16976,HOUSTON,TX,GMC,SIERRA,35900,Truck,2,0.793538,490074,"2,340,814"
28,28,19980,2011,60275,HOUSTON,TX,BMW,3,45000,Sedan,7,0.444000,490074,"2,340,814"
29,29,28990,2014,30662,HOUSTON,TX,JEEP,GRAND,31695,SUV,4,0.914655,490074,"2,340,814"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093,1093,11900,2015,33845,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.374449,444975,"1,573,688"
1094,1094,16495,2016,10078,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.519037,444975,"1,573,688"
1095,1095,26730,2015,42351,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,3,0.843351,444975,"1,573,688"
1096,1096,31480,2014,63354,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,4,0.993217,444975,"1,573,688"
1097,1097,10826,2008,62678,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,10,0.341568,444975,"1,573,688"
1098,1098,14500,2014,38388,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,4,0.456262,444975,"1,573,688"
1099,1099,28230,2014,44982,PHILADELPHIA,PA,GMC,SIERRA,35900,Truck,4,0.786351,444975,"1,573,688"
1100,1100,12699,2015,42127,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.399591,444975,"1,573,688"
1101,1101,14980,2016,40941,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.471366,444975,"1,573,688"
1102,1102,13480,2016,30244,PHILADELPHIA,PA,VOLKSWAGEN,JETTA,24500,Sedan,2,0.550204,444975,"1,573,688"
1103,1103,11900,2015,42362,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.374449,444975,"1,573,688"
1104,1104,17000,2015,44497,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.534928,444975,"1,573,688"
1105,1105,33980,2015,36989,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,3,0.889529,444975,"1,573,688"
1106,1106,13995,2015,34807,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.440371,444975,"1,573,688"
1107,1107,14980,2016,29660,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.471366,444975,"1,573,688"
1108,1108,12730,2012,39915,PHILADELPHIA,PA,HYUNDAI,SANTA,29800,SUV,6,0.427181,444975,"1,573,688"
1109,1109,10790,2012,82753,PHILADELPHIA,PA,HONDA,ACCORD,27470,Sedan,6,0.392792,444975,"1,573,688"
1110,1110,20730,2017,10069,PHILADELPHIA,PA,HYUNDAI,SANTA,29800,SUV,1,0.695638,444975,"1,573,688"
1111,1111,37230,2016,23484,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,2,0.974607,444975,"1,573,688"
1112,1112,29030,2015,19973,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,3,0.759948,444975,"1,573,688"
1113,1113,26980,2014,46892,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,4,0.851238,444975,"1,573,688"
1114,1114,24980,2016,8676,PHILADELPHIA,PA,HONDA,ACCORD,27470,Sedan,2,0.909356,444975,"1,573,688"
1115,1115,12995,2014,36151,PHILADELPHIA,PA,VOLKSWAGEN,JETTA,24500,Sedan,4,0.530408,444975,"1,573,688"
1116,1116,14900,2015,19646,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.468848,444975,"1,573,688"
1117,1117,14795,2010,29972,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,8,0.387304,444975,"1,573,688"
1118,1118,26780,2015,39899,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,3,0.844928,444975,"1,573,688"
1119,1119,25980,2015,40354,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,3,0.680105,444975,"1,573,688"
1120,1120,29730,2016,18313,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,2,0.778272,444975,"1,573,688"
1121,1121,7995,2010,147254,PHILADELPHIA,PA,BMW,3,45000,Sedan,8,0.177667,444975,"1,573,688"
1122,1122,13495,2016,45438,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.424638,444975,"1,573,688"

In [3]:
FinalData.drop(FinalData.columns[0],axis=1,inplace=True)

In [4]:
FinalData['Population'] = pd.to_numeric(FinalData['Population'], errors='coerce')
FinalData['Population'] = FinalData['Population'].astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
lm = sm.OLS(FinalData.DepreciationRate, sm.add_constant(FinalData.Population)).fit()

In [5]:
FinalData

,Price,Year,Mileage,City,State,Make,Model,Original Price,Vehicle Type,serviceTime,DepreciationRate,Gdp,Population
0,15893,2015,30608,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,3,0.500094,490074,NaN
1,13950,2015,95099,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,3,0.438955,490074,NaN
2,29900,2015,24384,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,3,0.782723,490074,NaN
3,26505,2014,42980,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.693848,490074,NaN
4,16400,2017,25446,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,1,0.516048,490074,NaN
5,18991,2014,33658,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,4,0.597577,490074,NaN
6,34000,2014,63120,HOUSTON,TX,GMC,SIERRA,35900,Truck,4,0.947075,490074,NaN
7,27988,2014,30321,HOUSTON,TX,GMC,SIERRA,35900,Truck,4,0.779610,490074,NaN
8,17986,2015,21448,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,3,0.654751,490074,NaN
9,24977,2014,29344,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.653848,490074,NaN
10,34459,2015,94129,HOUSTON,TX,FORD,F-1504WD,34695,Truck,3,0.993198,490074,NaN
11,14225,2016,36317,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,2,0.447609,490074,NaN
12,9999,2004,167182,HOUSTON,TX,JEEP,GRAND,31695,SUV,14,0.315476,490074,NaN
13,15995,2014,40576,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,4,0.503304,490074,NaN
14,15449,2015,34834,HOUSTON,TX,NISSAN,ALTIMA2.5,31780,Sedan,3,0.486123,490074,NaN
15,15995,2008,83493,HOUSTON,TX,FORD,F-1504WD,34695,Truck,10,0.461017,490074,NaN
16,9499,2008,115338,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,10,0.345795,490074,NaN
17,30789,2014,32943,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.805995,490074,NaN
18,12995,2013,90214,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,5,0.473062,490074,NaN
19,29988,2014,83803,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,4,0.785026,490074,NaN
20,21493,2017,36715,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,1,0.782417,490074,NaN
21,25884,2013,35832,HOUSTON,TX,CHEVROLET,SILVERADO,38200,Truck,5,0.677592,490074,NaN
22,12491,2010,71120,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,8,0.454714,490074,NaN
23,24525,2011,123507,HOUSTON,TX,GMC,SIERRA,35900,Truck,7,0.683148,490074,NaN
24,32998,2014,43840,HOUSTON,TX,GMC,SIERRA,35900,Truck,4,0.919164,490074,NaN
25,21500,2015,37699,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,3,0.782672,490074,NaN
26,4495,2004,141014,HOUSTON,TX,HONDA,ACCORD,27470,Sedan,14,0.163633,490074,NaN
27,28488,2016,16976,HOUSTON,TX,GMC,SIERRA,35900,Truck,2,0.793538,490074,NaN
28,19980,2011,60275,HOUSTON,TX,BMW,3,45000,Sedan,7,0.444000,490074,NaN
29,28990,2014,30662,HOUSTON,TX,JEEP,GRAND,31695,SUV,4,0.914655,490074,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093,11900,2015,33845,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.374449,444975,NaN
1094,16495,2016,10078,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.519037,444975,NaN
1095,26730,2015,42351,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,3,0.843351,444975,NaN
1096,31480,2014,63354,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,4,0.993217,444975,NaN
1097,10826,2008,62678,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,10,0.341568,444975,NaN
1098,14500,2014,38388,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,4,0.456262,444975,NaN
1099,28230,2014,44982,PHILADELPHIA,PA,GMC,SIERRA,35900,Truck,4,0.786351,444975,NaN
1100,12699,2015,42127,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.399591,444975,NaN
1101,14980,2016,40941,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.471366,444975,NaN
1102,13480,2016,30244,PHILADELPHIA,PA,VOLKSWAGEN,JETTA,24500,Sedan,2,0.550204,444975,NaN
1103,11900,2015,42362,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.374449,444975,NaN
1104,17000,2015,44497,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.534928,444975,NaN
1105,33980,2015,36989,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,3,0.889529,444975,NaN
1106,13995,2015,34807,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.440371,444975,NaN
1107,14980,2016,29660,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.471366,444975,NaN
1108,12730,2012,39915,PHILADELPHIA,PA,HYUNDAI,SANTA,29800,SUV,6,0.427181,444975,NaN
1109,10790,2012,82753,PHILADELPHIA,PA,HONDA,ACCORD,27470,Sedan,6,0.392792,444975,NaN
1110,20730,2017,10069,PHILADELPHIA,PA,HYUNDAI,SANTA,29800,SUV,1,0.695638,444975,NaN
1111,37230,2016,23484,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,2,0.974607,444975,NaN
1112,29030,2015,19973,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,3,0.759948,444975,NaN
1113,26980,2014,46892,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,4,0.851238,444975,NaN
1114,24980,2016,8676,PHILADELPHIA,PA,HONDA,ACCORD,27470,Sedan,2,0.909356,444975,NaN
1115,12995,2014,36151,PHILADELPHIA,PA,VOLKSWAGEN,JETTA,24500,Sedan,4,0.530408,444975,NaN
1116,14900,2015,19646,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,3,0.468848,444975,NaN
1117,14795,2010,29972,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,8,0.387304,444975,NaN
1118,26780,2015,39899,PHILADELPHIA,PA,JEEP,GRAND,31695,SUV,3,0.844928,444975,NaN
1119,25980,2015,40354,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,3,0.680105,444975,NaN
1120,29730,2016,18313,PHILADELPHIA,PA,CHEVROLET,SILVERADO,38200,Truck,2,0.778272,444975,NaN
1121,7995,2010,147254,PHILADELPHIA,PA,BMW,3,45000,Sedan,8,0.177667,444975,NaN
1122,13495,2016,45438,PHILADELPHIA,PA,NISSAN,ALTIMA2.5,31780,Sedan,2,0.424638,444975,NaN

In [ ]:
print(lm.summary())

In [ ]:
FinalData.describe()

In [ ]:
FinalData.Make.value_counts()

In [ ]:
plt.scatter(FinalData.Mileage,FinalData.DepreciationRate)
plt.plot(FinalData.Mileage, lm.predict(), color = 'black', c = 'DarkBlue')
plt.show()